name: Check Python Version

on:
  push:
    branches:
      - check_python_version

jobs:
  check_python_version_job:
    name: Check Python Version
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Display Python Version
        run: python --version
